FROM python:3.4-alpine

RUN mkdir /code

WORKDIR /code

ADD  requirements.txt /code/
ADD . /code/

RUN pip install  --upgrade pip
RUN pip install -r requirements.txt

#install pyfinder module in the container
RUN python setup.py install

COPY ./entryCrawler.py /code
ENTRYPOINT ["python","/code/entryCrawler.py" ]
CMD ["--help"]