FROM python:3.4-alpine

RUN mkdir /code

WORKDIR /code

ADD  requirements.txt /code/
ADD . /code/

# -v host/dir:guest/dir
# Note: The host directory is, by its nature, host-dependent. For this reason, you can’t mount a host directory from
# Dockerfile because built images should be portable. A host directory wouldn’t be available on all potential hosts.
# VOLUME /var/run/docker.sock

RUN pip install  --upgrade pip
RUN pip install -r requirements.txt

#install pyfinder module in the container
#ADD setup.py /code
RUN python setup.py install

#COPY ./start_scanner.py /code
ENTRYPOINT ["python","/code/start_scanner.py"]
CMD ["--help"]

#CMD ["run"]