FROM python:3.4-alpine

RUN mkdir /code

WORKDIR /code

#ADD  requirements.txt /code/
ADD . /code/

VOLUME /var/run/docker.sock /var/run/docker.sock

RUN pip install  --upgrade pip
RUN pip install -r requirements.txt

#install pyfinder module in the container
RUN python setup.py install

COPY ./start_scanner.py /code
ENTRYPOINT ["python","/code/start_scanner.py"]

#CMD ["--help"]

CMD ["run"]