FROM ubuntu:16.04


RUN apt-get update && apt-get install -y \
                build-essential checkinstall \
                python \
                python-pip \
                default-jre \
                php \
                ruby \
                nodejs \
                npm \
                groovy \
                scala \
                nginx \
                apache2 \
                gunicorn \
                perl \
                nano \
                curl \
                wget \


