FROM python:3.4-alpine

RUN mkdir /code

WORKDIR /code

COPY pyFinder/requirements.txt /code/

# install the requirements
RUN pip install  --upgrade pip
RUN pip install -r requirements.txt

# install pyfinder module in the container
# RUN python setup.py install

# copy the source code in the /code folder of the container
COPY pyFinder/ /code

ENTRYPOINT ["python","/code/entryCrawler.py" ]
CMD ["--help"]
