#scanner image
FROM python:alpine

RUN mkdir /code

WORKDIR /code

COPY  pyFinder/requirements.txt /code/

RUN pip install  --upgrade pip
RUN pip install -r requirements.txt

# ADD . /code/

COPY pyFinder/ /code

COPY deploy-package/analysis.py /code/pyfinder

ENTRYPOINT ["python","/code/entryScanner.py"]
CMD ["--help"]
